name = "LinearCovariance"
uuid = "4af8ee2a-afa9-11e9-10dc-fb1b37f8f4b5"
authors = ["Sascha Timme <sascha.timme@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
